"simple equation": "一次方程式"       
"quadratic equation": "二次方程式"       
"binomial theorem": "二項式定理"       
"tenth": "十分位"           
"parenthesis": "小括號"           
"segment": "弓形"             
"decimal": "小數"             
"bracket": "中括號"           
"ratio": "比"               
"proportional mean": "比例中項"         
"mean term": "內項"             
"incircle": "內切圓"           
"incenter": "內心  "           
"common difference": "公差"             
"common factor (divisor)": "公因數"           
"ascending power": "升羃"             
"point of tangency(contact)": "切點"             
"fraction": "分數"             
"denominator": "分母"             
"numerator": "分子"             
"analysis": "分析"             
"supplementary": "互補"             
"coprime (relatively prime)": "互質"             
"square": "平方"             
"straight angle": "平角"             
"parallel lines": "平行線"           
"cube root": "立方根"           
"cube": "立方"             
"amount": "本利和"           
"positive integer": "正整數"           
"square": "正方形"           
"extreme term": "外項"             
"external common tangent": "外公切線"         
"excenter (tircumcenter)": "外心"             
"addition": "加法"             
"add": "加"               
"addend": "加數"             
"elimination by substitution": "代入消去法"       
"quadrilateral": "四邊形"           
"power": "次方"             
"congruent triangles": "全等三角形"       
"polynomial": "多項式"           
"hundredth": "百分位"           
"concentric circles": "同心圓"           
"similar terms": "同類項"           
"annual rate of interest": "年利率"           
"interest": "利息"             
"included angle": "夾角"             
"foot": "呎"               
"frustum of a pyramid": "角台"             
"pyramid": "角錐"             
"arm": "股"               
"rectangular coordinates": "直角坐標"         
"ruler": "直尺"             
"diameter": "直徑"             
"right triangle": "直角三角形"       
"cuboid": "長方體"           
"odd number": "奇數"             
"radian": "弧度"             
"area of a surface": "表面積"           
"base angle": "底角"             
"function": "函數"             
"first term": "首項"             
"plane": "面"               
"negative": "負的"             
"degree": "度"               
"orthocenter": "垂心  "           
"adjacent": "相鄰"             
"barycenter": "重心"             
"double root": "重根"             
"distinct roots": "相異根"           
"coefficient": "係數"             
"division": "除法"             
"divisor": "除數"             
"multiplier": "乘數"             
"product formulae": "乘法公式"         
"radical": "根號"             
"escenter": "旁心"             
"multiplicand": "被乘數"           
"minuend": "被減數"           
"proper fraction": "真分數"           
"counterclockwise": "逆時鐘方向"       
"origin": "原點"             
"continues proportion": "連比例"           
"descending power": "降羃"             
"quotient": "商"               
"cardinal number": "基數"             
"vertex angle": "頂角"             
"improper fraction": "假分數"           
"reduction of fractions to a common denominator": "通分"             
"Pythagorean theorem": "畢氏定理"         
"golden section": "黃金分割"         
"arithmetic sequence": "等差數列"         
"arithmetic series": "等差級數"         
"common ratio sequence": "等比數列"         
"isosceles trapezoid": "等腰梯形"         
"equal root": "等根"             
"supplementary angle": "補角"             
"obtuse triangle": "鈍角三角形"       
"subtraction": "減法"             
"minus": "減"               
"irrational number": "無理數"           
"clockwise": "順時鐘方向"       
"quadrant": "象限"             
"greatest common divisor (g.c.d)": "最大公因數"       
"rhombus": "菱形"             
"imaginary line": "虛線"             
"imaginary number": "虛數"             
"calculus": "微積分"           
"extraction of root": "開方法"           
"center of a circle": "圓心"             
"central angle": "圓心角"           
"circumference of a circle": "圓周"             
"ratio of the circumference of the circle to the diameter": "圓周率"           
"circumference": "圓周長"           
"polynomial of degree zero": "零次多項式"       
"opposite side": "對邊"             
"diagonal": "對角線"           
"antiprism": "對角柱"           
"arithmetic mean": "算術平均數"       
"mathematical induction": "數學歸納法"       
"mathematician": "數學家"           
"slit": "截線"             
"complement angle": "餘角"             
"prime": "質數(素數)"
"acute angle": "銳角"             
"compound interest": "複利"             
"line": "線"               
"integer (whole number)": "整數"             
"integral number": "整數"             
"point": "點"               
"simultaneous equations": "聯立方程式"       
"axis of ordinates": "縱坐標軸"         
"volume": "體積"             
"general expression": "一般式"           
"icosahedron": "二十面體"         
"tens' digit": "十位數"           
"octagon": "八邊形"           
"brace": "大括號"           
"hexagon": "六邊形"           
"recurring period": "小數的循環節"     
"perpendicular bisector": "中垂線"           
"proportional segment": "比例線段"         
"interior alternate angle": "內錯角"           
"internal contact": "內切"             
"internal common tangent": "內公切線"         
"common ratio": "公比"             
"common tangent": "公切線"           
"pentagon": "五邊形"           
"tangent": "切線"             
"last term": "末項"             
"construction with ruler and compasses": "尺規作圖"         
"detached coefficient": "分離係數"         
"cardioid": "心臟線"           
"complementary": "互餘"             
"inquality": "不等式"           
"square root": "平方根"           
"parallelogram": "平行四邊形"       
"parallel": "平行"             
"hexahedron (cube)": "立方體"           
"radius": "半徑"             
"positive": "正的"             
"equilateral triangle": "正三角形"         
"direct proportion": "正比例"           
"circumcircle": "外接圓"           
"external contact": "外切"             
"external bisector": "外角平分線"       
"elimination by addition or subtraction": "加減消去法"       
"acceleration": "加速度"           
"algebra": "代數"             
"and": "且"               
"inch": "吋"               
"identical": "全等"             
"hundreds’ digit": "百位數"           
"percent": "百分比"           
"corresponding angles": "同位角"           
"rational number": "有理數"           
"point of intersection": "交點"             
"included side": "夾邊"             
"non-negative": "非負的"           
"coordinate planes": "坐標平面"         
"prism": "角柱"             
"ordinal number": "序數"             
"bisector of an angle": "角平分線"         
"rectilinear coordinates": "直線坐標"         
"right angle": "直角"             
"chord": "弦"               
"rectangle": "長方形"           
"natural number": "自然數"           
"sum": "和"               
"arc length": "弧長"             
"approximate value": "近似值"           
"graph of a function": "函數圖形"         
"parabola": "拋物線"           
"exponent": "指數"             
"area": "面積"             
"negative number": "負數"             
"perpendicular lines": "垂線"             
"similar triangles": "相似三角形"       
"antecedent": "前項"             
"barycenter": "重心"             
"center of gravity": "重心"             
"reduction of a fraction": "約分"             
"identity": "恆等式"           
"divide": "除"               
"multiplication": "乘法"             
"multiply": "乘"               
"sector": "扇形"             
"altitude (height)": "高"               
"dividend": "被除數"           
"summand": "被加數"           
"units’ digit": "個位數"           
"difference": "差"               
"defective item": "缺項"             
"radicand": "被開方數"         
"sphere": "球"               
"even number": "偶數"             
"hypotenuse-leg theorem": "商高定理"         
"base": "基底"             
"hypotenuse (leg)": "斜邊"             
"velocity": "速度"             
"constant term": "常數項"           
"mode": "眾數"             
"golden rectangle": "黃金矩形"         
"arithmetic mean": "等差中項"         
"common ratio progression": "等比級數"         
"common ratio mean": "等比中項"         
"isosceles triangle": "等腰三角形"       
"absolute value": "絕對值"           
"trapezoid": "梯形"             
"obtuse angle": "鈍角"             
"subtrahend": "減數"             
"sign of subtraction": "減號"             
"simple interest": "單利"             
"distance formula": "距離公式"         
"geometry": "幾何"             
"least common multiple (l.c.m)": "最小公倍數"       
"recurring decimal": "循環小數"         
"imaginary axis": "虛軸"             
"azimuth": "幅角"             
"secant": "割線"             
"radication": "開方"             
"angle in circular segment": "圓周角"           
"angle of circumference": "圓周角"           
"cylinder": "圓柱"             
"cone": "圓錐"             
"compasses": "圓規"             
"frustum of a cone": "圓台"             
"Plumb line": "鉛垂線"           
"vertical angle": "對頂角"           
"axis of symmetry": "對稱軸"           
"logarithm": "對數"             
"arithmetic": "算術"             
"mathematics": "數學"             
"digit": "數字"             
"asymptote": "漸近線"           
"remainder": "餘數"             
"prime divisor (factor)": "質因數"           
"acute triangle": "銳角三角形"       
"real line": "實線"             
"mid-point of a line segment": "線段中點"         
"product": "積"               
"axis of abscissas": "橫坐標軸"         
"division algorithm": "輾轉相除法"       
"helix": "螺線"             
"hyperbola": "雙曲線"           
"variable": "變數"             
