# -*- encoding : utf-8 -*-
# == Schema Information
#
# Table name: mappings
#
#  id         :integer          not null, primary key
#  before     :string(255)
#  after      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Mapping < ActiveRecord::Base
  attr_accessible :before, :after

  def self.init
    [
      ["一次方程式", "simple equation"],
      ["二次方程式", "quadratic equation"],
      ["二項式定理", "binomial theorem"],
      ["十分位", "tenth"],
      ["小括號", "parenthesis"],
      ["弓形", "segment"],
      ["小數", "decimal"],
      ["中括號", "bracket"],
      ["比", "ratio"],
      ["比例中項", "proportional mean"],
      ["內項", "mean term"],
      ["內切圓", "incircle"],
      ["內心  ", "incenter"],
      ["公差", "common difference"],
      ["公因數", "common factor (divisor)"],
      ["升羃", "ascending power"],
      ["切點", "point of tangency(contact)"],
      ["分數", "fraction"],
      ["分母", "denominator"],
      ["分子", "numerator"],
      ["分析", "analysis"],
      ["互補", "supplementary"],
      ["互質", "coprime (relatively prime)"],
      ["平方", "square"],
      ["平角", "straight angle"],
      ["平行線", "parallel lines"],
      ["立方根", "cube root"],
      ["立方", "cube"],
      ["本利和", "amount"],
      ["正整數", "positive integer"],
      ["正方形", "square"],
      ["外項", "extreme term"],
      ["外公切線", "external common tangent"],
      ["外心", "excenter (tircumcenter)"],
      ["加法", "addition"],
      ["加", "add"],
      ["加數", "addend"],
      ["代入消去法", "elimination by substitution"],
      ["四邊形", "quadrilateral"],
      ["次方", "power"],
      ["全等三角形", "congruent triangles"],
      ["多項式", "polynomial"],
      ["百分位", "hundredth"],
      ["同心圓", "concentric circles"],
      ["同類項", "similar terms"],
      ["年利率", "annual rate of interest"],
      ["利息", "interest"],
      ["夾角", "included angle"],
      ["呎", "foot"],
      ["角台", "frustum of a pyramid"],
      ["角錐", "pyramid"],
      ["股", "arm"],
      ["直角坐標", "rectangular coordinates"],
      ["直尺", "ruler"],
      ["直徑", "diameter"],
      ["直角三角形", "right triangle"],
      ["長方體", "cuboid"],
      ["奇數", "odd number"],
      ["弧度", "radian"],
      ["表面積", "area of a surface"],
      ["底角", "base angle"],
      ["函數", "function"],
      ["首項", "first term"],
      ["面", "plane"],
      ["負的", "negative"],
      ["度", "degree"],
      ["垂心  ", "orthocenter"],
      ["相鄰", "adjacent"],
      ["重心", "barycenter"],
      ["重根", "double root"],
      ["相異根", "distinct roots"],
      ["係數", "coefficient"],
      ["除法", "division"],
      ["除數", "divisor"],
      ["乘數", "multiplier"],
      ["乘法公式", "product formulae"],
      ["根號", "radical"],
      ["旁心", "escenter"],
      ["被乘數", "multiplicand"],
      ["被減數", "minuend"],
      ["真分數", "proper fraction"],
      ["逆時鐘方向", "counterclockwise"],
      ["原點", "origin"],
      ["連比例", "continues proportion"],
      ["降羃", "descending power"],
      ["商", "quotient"],
      ["基數", "cardinal number"],
      ["頂角", "vertex angle"],
      ["假分數", "improper fraction"],
      ["通分", "reduction of fractions to a common denominator"],
      ["畢氏定理", "Pythagorean theorem"],
      ["黃金分割", "golden section"],
      ["等差數列", "arithmetic sequence"],
      ["等差級數", "arithmetic series"],
      ["等比數列", "common ratio sequence"],
      ["等腰梯形", "isosceles trapezoid"],
      ["等根", "equal root"],
      ["補角", "supplementary angle"],
      ["鈍角三角形", "obtuse triangle"],
      ["減法", "subtraction"],
      ["減", "minus"],
      ["無理數", "irrational number"],
      ["順時鐘方向", "clockwise"],
      ["象限", "quadrant"],
      ["最大公因數", "greatest common divisor (g.c.d)"],
      ["菱形", "rhombus"],
      ["虛線", "imaginary line"],
      ["虛數", "imaginary number"],
      ["微積分", "calculus"],
      ["開方法", "extraction of root"],
      ["圓心", "center of a circle"],
      ["圓心角", "central angle"],
      ["圓周", "circumference of a circle"],
      ["圓周率", "ratio of the circumference of the circle to the diameter"],
      ["圓周長", "circumference"],
      ["零次多項式", "polynomial of degree zero"],
      ["對邊", "opposite side"],
      ["對角線", "diagonal"],
      ["對角柱", "antiprism"],
      ["算術平均數", "arithmetic mean"],
      ["數學歸納法", "mathematical induction"],
      ["數學家", "mathematician"],
      ["截線", "slit"],
      ["餘角", "complement angle"],
      ["質數(素數)", "prime"],
      ["銳角", "acute angle"],
      ["複利", "compound interest"],
      ["線", "line"],
      ["整數", "integer (whole number)"],
      ["整數", "integral number"],
      ["點", "point"],
      ["聯立方程式", "simultaneous equations"],
      ["縱坐標軸", "axis of ordinates"],
      ["體積", "volume"],
      ["一般式", "general expression"],
      ["二十面體", "icosahedron"],
      ["十位數", "tens' digit"],
      ["八邊形", "octagon"],
      ["大括號", "brace"],
      ["六邊形", "hexagon"],
      ["小數的循環節", "recurring period"],
      ["中垂線", "perpendicular bisector"],
      ["比例線段", "proportional segment"],
      ["內錯角", "interior alternate angle"],
      ["內切", "internal contact"],
      ["內公切線", "internal common tangent"],
      ["公比", "common ratio"],
      ["公切線", "common tangent"],
      ["五邊形", "pentagon"],
      ["切線", "tangent"],
      ["末項", "last term"],
      ["尺規作圖", "construction with ruler and compasses"],
      ["分離係數", "detached coefficient"],
      ["心臟線", "cardioid"],
      ["互餘", "complementary"],
      ["不等式", "inquality"],
      ["平方根", "square root"],
      ["平行四邊形", "parallelogram"],
      ["平行", "parallel"],
      ["立方體", "hexahedron (cube)"],
      ["半徑", "radius"],
      ["正的", "positive"],
      ["正三角形", "equilateral triangle"],
      ["正比例", "direct proportion"],
      ["外接圓", "circumcircle"],
      ["外切", "external contact"],
      ["外角平分線", "external bisector"],
      ["加減消去法", "elimination by addition or subtraction"],
      ["加速度", "acceleration"],
      ["代數", "algebra"],
      ["且", "and"],
      ["吋", "inch"],
      ["全等", "identical"],
      ["百位數", "hundreds’ digit"],
      ["百分比", "percent"],
      ["同位角", "corresponding angles"],
      ["有理數", "rational number"],
      ["交點", "point of intersection"],
      ["夾邊", "included side"],
      ["非負的", "non-negative"],
      ["坐標平面", "coordinate planes"],
      ["角柱", "prism"],
      ["序數", "ordinal number"],
      ["角平分線", "bisector of an angle"],
      ["直線坐標", "rectilinear coordinates"],
      ["直角", "right angle"],
      ["弦", "chord"],
      ["長方形", "rectangle"],
      ["自然數", "natural number"],
      ["和", "sum"],
      ["弧長", "arc length"],
      ["近似值", "approximate value"],
      ["函數圖形", "graph of a function"],
      ["拋物線", "parabola"],
      ["指數", "exponent"],
      ["面積", "area"],
      ["負數", "negative number"],
      ["垂線", "perpendicular lines"],
      ["相似三角形", "similar triangles"],
      ["前項", "antecedent"],
      ["重心", "barycenter"],
      ["重心", "center of gravity"],
      ["約分", "reduction of a fraction"],
      ["恆等式", "identity"],
      ["除", "divide"],
      ["乘法", "multiplication"],
      ["乘", "multiply"],
      ["扇形", "sector"],
      ["高", "altitude (height)"],
      ["被除數", "dividend"],
      ["被加數", "summand"],
      ["個位數", "units’ digit"],
      ["差", "difference"],
      ["缺項", "defective item"],
      ["被開方數", "radicand"],
      ["球", "sphere"],
      ["偶數", "even number"],
      ["商高定理", "hypotenuse-leg theorem"],
      ["基底", "base"],
      ["斜邊", "hypotenuse (leg)"],
      ["速度", "velocity"],
      ["常數項", "constant term"],
      ["眾數", "mode"],
      ["黃金矩形", "golden rectangle"],
      ["等差中項", "arithmetic mean"],
      ["等比級數", "common ratio progression"],
      ["等比中項", "common ratio mean"],
      ["等腰三角形", "isosceles triangle"],
      ["絕對值", "absolute value"],
      ["梯形", "trapezoid"],
      ["鈍角", "obtuse angle"],
      ["減數", "subtrahend"],
      ["減號", "sign of subtraction"],
      ["單利", "simple interest"],
      ["距離公式", "distance formula"],
      ["幾何", "geometry"],
      ["最小公倍數", "least common multiple (l.c.m)"],
      ["循環小數", "recurring decimal"],
      ["虛軸", "imaginary axis"],
      ["幅角", "azimuth"],
      ["割線", "secant"],
      ["開方", "radication"],
      ["圓周角", "angle in circular segment"],
      ["圓周角", "angle of circumference"],
      ["圓柱", "cylinder"],
      ["圓錐", "cone"],
      ["圓規", "compasses"],
      ["圓台", "frustum of a cone"],
      ["鉛垂線", "Plumb line"],
      ["對頂角", "vertical angle"],
      ["對稱軸", "axis of symmetry"],
      ["對數", "logarithm"],
      ["算術", "arithmetic"],
      ["數學", "mathematics"],
      ["數字", "digit"],
      ["漸近線", "asymptote"],
      ["餘數", "remainder"],
      ["質因數", "prime divisor (factor)"],
      ["銳角三角形", "acute triangle"],
      ["實線", "real line"],
      ["線段中點", "mid-point of a line segment"],
      ["積", "product"],
      ["橫坐標軸", "axis of abscissas"],
      ["輾轉相除法", "division algorithm"],
      ["螺線", "helix"],
      ["雙曲線", "hyperbola"],
      ["變數", "variable"]
    ].each do |obj|
      Mapping.create(:after => obj[0], :before => obj[1])
    end
  end
end
